version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/martinsirbe/docker-js-yaml-format
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: Build a docker image.
          command: make build
      - run:
          name: Push to the docker registries.
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push martinsirbe/docker-js-yaml-format:$(git rev-parse --short $CIRCLE_SHA1)
            docker push martinsirbe/docker-js-yaml-format:latest
            echo "$GITHUB_PKG_REG_TOKEN" | docker login docker.pkg.github.com -u "$GITHUB_USERNAME" --password-stdin
            docker push docker.pkg.github.com/martinsirbe/docker-js-yaml-format/docker-js-yaml-format:$(git rev-parse --short $CIRCLE_SHA1)
            docker push docker.pkg.github.com/martinsirbe/docker-js-yaml-format/docker-js-yaml-format:latest
workflows:
  version: 2
  commit:
    jobs:
      - build:
          filters:
            branches:
              only: master
  periodic-build:
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
